name: shiny.react JS test

on: push

jobs:
  test-shiny-react:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: yarn install
        run: yarn install
        working-directory: js

      - name: yarn lint
        run: yarn lint
        working-directory: js

      - name: yarn test
        run: yarn test
        working-directory: js
